default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: ruby_hotel_development
  username: <%= ENV['PG_LOGIN']%>
  password: <%= ENV['PG_PASSWORD']%>
  pool: 5

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
